services:
  movix:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movix-app
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "3014:3014"
